services:
  - type: web
    name: movie-recommendation-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: TMDB_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
